### ISSUE TITLE
Add JS Closures Princess story

### ISSUE THREAD

**Issue by theRemix** [devleague/DevLeague-Modules#133]
pick one, and add to our closures module (JS Foundations)

then make PR

1. http://stackoverflow.com/questions/111102/how-do-javascript-closures-work/6472397#6472397
1. https://rakhish.wordpress.com/2017/02/08/story-of-js-closures/

**Comment by jaywon** [comment]
Why not both? .... if both are helpful 🤔

**Comment by sgnl** [comment]
Princess story as a gist: https://gist.github.com/sgnl/9a168d695373f09f64d5dee7d985bd99
