### ISSUE TITLE
DevCast: How to Setup Sublime Text Package Control

### ISSUE THREAD

**Issue by JoeKarlsson1** [devleague/DevLeague-Modules#26]
https://www.youtube.com/watch?v=js7kt0LBlWA

**Comment by jaywon** [comment]
https://docs.google.com/document/d/1fwvyEZ4SeW4S_0vECptb51jWEX5qmlO5zWMwjVhuE-4/edit

**Comment by JoeKarlsson1** [comment]
Video finished, need to upload it to Google Drive for approval.
