### ISSUE TITLE
document dataset sources somewhere

### ISSUE THREAD

**Issue by theRemix** [devleague/DevLeague-Modules#38]
find a google doc, or wiki page, or somewhere to add_or_create a list of useful datasources for final projects
here is first entry:
https://github.com/caesar0301/awesome-public-datasets

**Comment by JoeKarlsson1** [comment]
Added a bunch of API Datasets to the Final Project Module

**Comment by JoeKarlsson1** [comment]
https://github.com/devleague/final-project-guidelines/blob/master/README.md

**Comment by JoeKarlsson1** [comment]
## Resources
- [Programmable Web](http://www.programmableweb.com/apis/directory)
  - With over "14,000" APIs to choose from, surely you'll be inspired. Beware of old apis or broken api links. YMMV
- [Data.gov](https://www.data.gov/)
  - A civil-focused Api.
- [data.hawaii.gov](https://data.hawaii.gov/)
- [Awesome Public Datasets](https://github.com/caesar0301/awesome-public-datasets)
  - shaka brah.
